site_name: Ilia Pavlovskii
site_url: https://ilyapavlovskii.github.io/IlyaPavlovskii
nav:
    - Introduction: 'index.md'
    - Android:
          - 'English':
                - 'Stop Refactoring. Kotlin. Android': 'android/english/stop-refactoring/index.md'
                - 'FeatureToggle cooking': 'android/english/feature-toggle/index.md'
                - 'Making a Custom Shape Widget on Jetpack Compose Using Figma and AndroidVectors': 'android/english/compose-vector-shape/index.md'
          - 'Russian':
                - 'Стоп рефакторинг. Kotlin. Android': 'android/russian/stop-refactoring/index.md'
                - 'Готовим FeatureToggle для Android': 'android/russian/feature-toggle/index.md'
                - 'Делаем виджет с кастомной формой на Jetpack Compose с помощью Figma и AndroidVectors': 'android/russian/compose-vector-shape/index.md'
    - Other:
        - 'English':
            - 'Shooting sport':  'other/english/shooting-sport/index.md'
        - 'Russian':
          - 'Год в Польше по PBH': 'other/russian/pbh/index.md'
          - 'Стрелковый спорт или новое хобби': 'other/russian/shooting-sport/index.md'
    - LinkedIn: "https://www.linkedin.com/in/ipavlovskii/"
    - GitHub: "https://github.com/IlyaPavlovskii/"
    - Habr: "https://habr.com/ru/users/TranE91/posts/"
    - Medium: "https://pavlovskiiilia.medium.com/"
theme:
    name: material
    locale: en
    include_sidebar: true